### PR TITLE
GDSC logo on RULES page #13

### PR DESCRIPTION
**Pull request by nitishapiplani**
GDSC logo on RULES page #13

### CODE REVIEW

**Review by Bhavya0404 — CHANGES_REQUESTED** [review]
can you make this logo less stretched?
You can refer the size from other css files.

**Comment by nitishapiplani** [comment]
changed width according to others

**Review by Bhavya0404 — APPROVED** [review]
Good Work!

**Comment by nitishapiplani** [comment]
> Good Work!

thank you

**Pull request merged**
