### PR TITLE
Made changes in size of images and text on goodies page

### PR DESCRIPTION
**Pull request by niku123K**

### CODE REVIEW

**Comment by niku123K** [comment]
I want to confirm about my pull request ,it is still not get merged is any implementation needed in it?

**Review by sarthakpant772 — COMMENTED** [review]
hey @niku123K , sorry we got buzy with some work. Talking about changes, it looks fine to me but let see what @Bhavya0404  thinks.

**Comment by MeenalPrakash** [comment]
Hey @niku123K , great work we are merging your pull request.

**Comment by niku123K** [comment]
Thank you so much !!

**Pull request merged**
