### PR TITLE
Added All The Files Of The Hactoberfest Website As Mentioned About Adding Animations And Beautiful Font Styles

### PR DESCRIPTION
**Pull request by code08-ind**
Added All The Files After Editing The Font Styles, Adding Animations And Transformations Along With Changes In Navbar.

### CODE REVIEW

**Comment by code08-ind** [comment]
Please Merge It

**Review by sarthakpant772 — CHANGES_REQUESTED** [review]
hey @code08-ind  looks good but it has some Conflicting files can u check on that

**Comment by code08-ind** [comment]
Closed

**Comment by code08-ind** [comment]
Merged All The Conflicts

**Comment by code08-ind** [comment]
Closed. Already Another PR Is Merged.

**Pull request closed without merging**
