### PR TITLE
rules page modified

### PR DESCRIPTION
**Pull request by shrutij11**
modified rules page

### CODE REVIEW

**Comment by shrutij11** [comment]
plz check it and let me know if any further changes required.

**Review by Bhavya0404 — CHANGES_REQUESTED** [review]
Can you reduce the margin-top between navbar and the content?

**Comment by shrutij11** [comment]
> Can you reduce the margin-top between navbar and the content?

@Bhavya0404 done the changes plz look into it.

**Review by sarthakpant772 — APPROVED** [review]
Great work @shrutij11.

**Pull request merged**
