### PR TITLE
about button decorated hover effect included

### PR DESCRIPTION
**Pull request by SahbanAlam**
Please accept it and mark  it under hacktoberfest.

### CODE REVIEW

**Comment by SahbanAlam** [comment]
This is my first time contributing to open source. If there's anything wrong with my code please do let me know.

**Comment by agarwalrashika00** [comment]
hey @SahbanAlam you did some nice changes to the button. Just try giving little border radius to it and change the color from dark to light on hovering over it. Also give a space between "HAPPY" and "HACKING!".

**Review by agarwalrashika00 — CHANGES_REQUESTED** [review]
hey @SahbanAlam you did some nice changes to the button. 
- Just try giving little **border radius** to it 
- change the bgcolor from **dark to light** on hovering over it
- Also give a **space** between "HAPPY" and "HACKING!".

**Review by agarwalrashika00 — APPROVED** [review]
great

**Comment by SahbanAlam** [comment]
thank you :D

**Pull request merged**
