### PR TITLE
Insertion of footer

### PR DESCRIPTION
**Pull request by Pensuveze**

### CODE REVIEW

**Review by sarthakpant772 — CHANGES_REQUESTED** [review]
Please try to make theme same as of home page and the social icons are not visible please try to change that.
image

**Comment by Pensuveze** [comment]
@sarthakpant772 Sure sir...I am working on it . will update you in an hour.

**Comment by Pensuveze** [comment]
@sarthakpant772 Please check it...

**Review by sarthakpant772 — CHANGES_REQUESTED** [review]
Footer looks fine.Great work .
Can you remove it from home page and add it on goodies and rules it would be geat of you can do that.

**Comment by Pensuveze** [comment]
@sarthakpant772 As this is a homepage I think footer is must.
So if you merge this Pull request and I will create a new issue for Goodies and Rule page and will do another PR .It would be great.
Thanks.

**Comment by Pensuveze** [comment]
@sarthakpant772 @Bhavya0404 sir please review my comment .

**Review by Bhavya0404 — APPROVED** [review]
Ok Great  Work!

**Review by sarthakpant772 — APPROVED** [review]

**Pull request merged**
