### PR TITLE
Add logo of Tab

### PR DESCRIPTION
**Pull request by vrushal007**
I have added tab logo of your website. It increase your website reputation. So please accept my pull request and see how it looks like. Thank you.

### CODE REVIEW

**Review by Bhavya0404 — CHANGES_REQUESTED** [review]
can you please add GDSC logo? It's there in our repo.

**Comment by vrushal007** [comment]
Okay. Thank you. I'll do it by today

**Comment by vrushal007** [comment]
I have completed. Please check and let me know if any issues is there.

**Review by Bhavya0404 — APPROVED** [review]
Great!

**Comment by vrushal007** [comment]
Thank you so much.

**Pull request merged**
