### PR TITLE
navbar improved(scrollbar removed)

### PR DESCRIPTION
**Pull request by PiyushNadoda**

### CODE REVIEW

**Review by sarthakpant772 — CHANGES_REQUESTED** [review]
Please do the same in goodies page too. 😄

**Comment by PiyushNadoda** [comment]
@sarthakpant772 I'll do it by today.

**Review by PiyushNadoda — COMMENTED** [review]
Chnages done.

**Review by sarthakpant772 — APPROVED** [review]
looks good to me. @Bhavya0404  please check on this.

**Comment by sarthakpant772** [comment]
amazing work @PiyushNadoda keep hustling. 👍🏼

**Comment by PiyushNadoda** [comment]
Thanks!!

**Pull request merged**
